export enum ExceptionsConstants {
  EMAIL_ALREADY_EXISTS = 'exceptions:EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND = 'exceptions:USER_NOT_FOUND',
  ROLE_NOT_FOUND = 'exceptions:ROLE_NOT_FOUND',
  INVALID_CREDENTIALS = 'exceptions:INVALID_CREDENTIALS',
  BAD_REQUEST = 'exceptions:BAD_REQUEST',
  INVALID_PASSWORD = 'exceptions:INVALID_PASSWORD',
  INVALID_OLD_EMAIL = 'exceptions:INVALID_OLD_EMAIL',
  FAILED_TO_DELETE_USER = 'exceptions:FAILED_TO_DELETE_USER',
  FAILED_TO_UPDATE_EMAIL = 'exceptions:FAILED_TO_UPDATE_EMAIL',
  FAILED_TO_UPDATE_PASSWORD = 'exceptions:FAILED_TO_UPDATE_PASSWORD'
}
